name: Preview

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - uses: netlify/actions/cli@master
        id: deploy-neflify
        with:
          args: deploy --dir=build/
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Find Deploy Comment
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.number }}
          comment-author: pythonpizzabot
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.find_comment.outputs.comment-id == null }}
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            This pull request is being automatically deployed to Netlify.

            🔍 Inspect: ${{ steps.deploy-neflify.outputs.NETLIFY_LOGS_URL }}
            ✅ Preview: ${{ steps.deploy-neflify.outputs.NETLIFY_URL }}
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.find_comment.outputs.comment-id != null }}
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.number }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          body: |
            This pull request is being automatically deployed to Netlify.

            🔍 Inspect: ${{ steps.deploy-neflify.outputs.NETLIFY_LOGS_URL }}
            ✅ Preview: ${{ steps.deploy-neflify.outputs.NETLIFY_URL }}
